.Dd January 20, 2023
.Dt CIDRL 1
.Os
.Sh NAME
.Nm cidrl
.Nd List all IPv4 Addresses within a CIDR block.
.Sh SYNOPSIS
.Nm
.Ar CIDR-block
.Sh DESCRIPTION
The
.Nm
utlity prints all IP addresses within a given CIDR block.
.Pp
.Sh EXAMPLES
List IPv4 addresses within a CIDR block:
.Pp
.Dl cidrl 192.168.50.16/29
.Sh BUGS
Issue tracker: <https://github.com/emden-norfolk/cidrl/issues>
.Sh AUTHOR
.An Damien Bezborodov
.Sh COPYRIGHT
Copyright \(co 2016 Damien Bezborodov
.br
BSD-3 license.
