#!/usr/bin/php
<?php

require_once __DIR__ .'/cidrl.php';

if ($argc != 2) {
	exit(1); // Not an argument.
}
cidrl($argv[1], $error_code, function($address) {
	print "$address\n";
});
if ($error_code !== 0) {
	exit($error_code); // Invalid IP address.
}
